### ISSUE TITLE
multiple character decoding errors when running load_data.py on mac

### ISSUE THREAD

**Issue by emkap01** [codefordc/housing-insights#163]
Per Neal's request, I'm writing up this ticket. I've made multiple attempts to run load_data.py inside the housing-insights environment while running the docker container from inside my local repo.  The first attempt resulted in the following error:

```
(housing-insights) :scripts $ python load_data.py docker rebuild
meta.json imported. JSON format is valid: True
Manifest table created in the SQL database
sql_manifest_exists: True
building_permits_2016: preparing to load row 3 from the manifest
  file not found. attempting to download file to disk: https://s3.amazonaws.com/housinginsights/raw/building_permits/2016/Building_Permits__2016_updated.csv
  download complete.
  do_fields_match: True. meta.json and csv field lists match completely for 'building_permits'
  Ready to clean building_permits
Traceback (most recent call last):
  File "load_data.py", line 167, in <module>
    main(database_choice, meta_path, manifest_path, keep_temp_files = True)
  File "load_data.py", line 116, in main
    for idx, data_row in enumerate(csv_reader):
  File "/Users/emkap01/HousingInsights/repo/housing-insights/python/housinginsights/ingestion/DataReader.py", line 43, in __iter__
    for row in reader:
  File "/Users/emkap01/miniconda3/envs/housing-insights/lib/python3.5/csv.py", line 110, in __next__
    row = next(self.reader)
  File "/Users/emkap01/miniconda3/envs/housing-insights/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 5936: invalid continuation byte
```

A subsequent attempt to run the script with the `sample` parameter resulted in a similar error message: 

```
acs_rent_median_09_5YR: preparing to load row 3 from the manifest
  do_fields_match: True. meta.json and csv field lists match completely for 'acs_rent_median_temp'
  Ready to clean acs_rent_median_temp
Traceback (most recent call last):
  File "load_data.py", line 167, in <module>
    main(database_choice, meta_path, manifest_path, keep_temp_files = True)
  File "load_data.py", line 116, in main
    for idx, data_row in enumerate(csv_reader):
  File "/Users/emkap01/HousingInsights/repo/housing-insights/python/housinginsights/ingestion/DataReader.py", line 43, in __iter__
    for row in reader:
  File "/Users/emkap01/miniconda3/envs/housing-insights/lib/python3.5/csv.py", line 110, in __next__
    row = next(self.reader)
  File "/Users/emkap01/miniconda3/envs/housing-insights/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 6506: invalid continuation byte
```

Final attempt to run the script without the `sample` parameter resulted in an error message for the file `https://s3.amazonaws.com/housinginsights/raw/preservation_catalog/20160401/Subsidy.csv`.

**Comment by louvis** [comment]
I came across the same kind of error when running the script with the ```sample``` parameter:

```(housing-insights) $ python load_data.py docker rebuild sample
meta_sample.json imported. JSON format is valid: True
Manifest table created in the SQL database
sql_manifest_exists: True
project_sample: preparing to load row 1 from the manifest
  do_fields_match: True. meta.json and csv field lists match completely for 'project_temp'
  Ready to clean project_temp
  Ready to load
  replacing existing table
  project_temp table can't be dropped because it doesn't exist
  Table created: project_temp
  opening /Users/Jay/Documents/Housing Insights/housing-insights/python/logs/temp_project_sample.psv
  data file loaded into database
acs_sample: preparing to load row 2 from the manifest
  do_fields_match: True. meta.json and csv field lists match completely for 'acs_rent_median_temp'
  Ready to clean acs_rent_median_temp
  Ready to load
  Table created: acs_rent_median_temp
  opening /Users/Jay/Documents/Housing Insights/housing-insights/python/logs/temp_acs_sample.psv
  data file loaded into database
acs_rent_median_09_5YR: preparing to load row 3 from the manifest
  do_fields_match: True. meta.json and csv field lists match completely for 'acs_rent_median_temp'
  Ready to clean acs_rent_median_temp
Traceback (most recent call last):
  File "load_data.py", line 167, in <module>
    main(database_choice, meta_path, manifest_path, keep_temp_files = True)
  File "load_data.py", line 116, in main
    for idx, data_row in enumerate(csv_reader):
  File "/Users/Jay/Documents/Housing Insights/housing-insights/python/housinginsights/ingestion/DataReader.py", line 43, in __iter__
    for row in reader:
  File "//anaconda/envs/housing-insights/lib/python3.5/csv.py", line 110, in __next__
    row = next(self.reader)
  File "//anaconda/envs/housing-insights/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 6506: invalid continuation byte```

**Comment by emkap01** [comment]
Repeating my Slack comment just to close the loop on this - 

For the most part it looks like the fix successfully resolved the character decoding issues.  It appears to have loaded almost all of the data, although I did get a few error messages at the end regarding missing files:

```
crime_2015: preparing to load row 64 from the manifest
  file not found. attempting to download file to disk: https://s3.amazonaws.com/housinginsights/raw/crime/mpd-crime-map/20170403/2015-all.csv
Traceback (most recent call last):
  File "/Users/emkap01/HousingInsights/repo/housing-insights/python/housinginsights/ingestion/DataReader.py", line 180, in download_data_file
    with open(self.path, 'r', newline='') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/emkap01/HousingInsights/repo/housing-insights/python/housinginsights/ingestion/../../../data/raw/crime/mpd-crime-map/20170403/2015-all.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "load_data.py", line 167, in <module>
    main(database_choice, meta_path, manifest_path, keep_temp_files = True)
  File "load_data.py", line 100, in main
    csv_reader = DataReader(meta = meta, manifest_row=manifest_row, load_from="file")
  File "/Users/emkap01/HousingInsights/repo/housing-insights/python/housinginsights/ingestion/DataReader.py", line 169, in __init__
    self.download_data_file()
  File "/Users/emkap01/HousingInsights/repo/housing-insights/python/housinginsights/ingestion/DataReader.py", line 185, in download_data_file
    urlretrieve(self.s3_path, self.path)
  File "/Users/emkap01/miniconda3/envs/housing-insights/lib/python3.5/urllib/request.py", line 198, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/emkap01/HousingInsights/repo/housing-insights/python/housinginsights/ingestion/../../../data/raw/crime/mpd-crime-map/20170403/2015-all.csv'
```

**Comment by NealHumphrey** [comment]
@emkap01 it looks like this is actually a different issue. I did some digging and identified this as due to the fact that the folder does not yet exist. I made a new ticket for this in #172 .
