### ISSUE TITLE
Error loading in *sample* data

### ISSUE THREAD

**Issue by jasonrhaas** [codefordc/housing-insights#246]
When trying to load in the sample data using the command `python load_data.py docker rebuild sample`, a Traceback occurs:

```
Traceback (most recent call last):
  File "load_data.py", line 175, in <module>
    main(database_choice, meta_path, manifest_path, keep_temp_files = True)
  File "load_data.py", line 111, in main
    name= cleaner_class_name)
  File "/code/python/housinginsights/ingestion/functions.py", line 106, in get_cleaner_from_name
    Class_ = getattr(Cleaners, name)
AttributeError: module 'housinginsights.ingestion.Cleaners' has no attribute 'ACSRentCleaner'
```

This is due to a few fields in the **meta.json** and **sample_meta.json** that have not been updated since a recent re-factoring.

**UPDATE**:  I have a fix for this, it is coming in a PR shortly.

**Comment by jasonrhaas** [comment]
This can be closed
