### ISSUE TITLE
Uncaught exception when going from building view back to map view. 

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#272]
@ostermanj to investigate later, doesn't appear to break any functionality. This applies to the refactored code versio in the current pull request #270 soon to be merged to dev. 

To recreate:

Go to /tool page
Navigate to a building view (I went to /tool/building.html?building=NL000360)
Click back button. 

This appears in console:
```
PubSub.js:55 Uncaught TypeError: Cannot read property 'length' of undefined
    at t (https://cdnjs.cloudflare.com/ajax/libs/d3/4.8.0/d3.min.js:5:23198)
    at Object.entries (https://cdnjs.cloudflare.com/ajax/libs/d3/4.8.0/d3.min.js:5:23683)
    at DonutChart.returnPieVariable (http://127.0.0.1:4000/tool/js/donut-chart.js:18:8)
    at http://127.0.0.1:4000/tool/js/sidebar-view.js:87:43
    at Array.forEach (native)
    at changeZoneType (http://127.0.0.1:4000/tool/js/sidebar-view.js:86:28)
    at callSubscriberWithDelayedExceptions (http://127.0.0.1:4000/tool/js/PubSub.js:61:13)
    at deliverMessage (http://127.0.0.1:4000/tool/js/PubSub.js:82:17)
    at deliverNamespaced (http://127.0.0.1:4000/tool/js/PubSub.js:93:13)
```

Nothing appears broken on page so might be non issue.

**Comment by NealHumphrey** [comment]
I tried doing a bit of digging to fix this. Couldn't quite trace it, but it appears to be related to sequencing of when the data is available vs. when this function is called.  the `chart.data` object is empty when changeZoneType is called. 

sidebar-view.js sets these three subscriptions:
```
setSubs([
            ['firstPieReady', sideBar.setDropdownOptions],
            ['mapLayer',sideBar.changeZoneType],
            ['pieZone', sideBar.changeZoneType]
        ]);
```

My guess is that if mapLayer finishes before firstPieReady it triggers the changeZoneType event but the data is null. 

This probably isn't a big deal since the user won't be able to alter the ward until the firstPieReady event happens. So maybe we want to just handle this with some sort of error handling where if chart.data doesn't exist it doesn't raise an error unless the firstPieReady event has occured? 

Also, we will likely change how these pie charts (or any similar substitutes) are created - we want to eliminate the ward dropdown and replace it with the a ward choice among the many filter choices, and tie any updates to pie to the filter event, so it might be a moot point.

**Comment by NealHumphrey** [comment]
This is no longer an issue as we are not using the Ward dropdown anymore.
