### ISSUE TITLE
202 response needs handling

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#285]
The opendata.py class (not yet merged to dev) can sometimes return a 202 status. This means the request has been accepted but not finished processing. We will need to poll the server to find out when it is available to be able to resolve this issue and successfully download the file. 

I'm not sure which file was being requested when this occurred (will update when I re-encounter the error)
```
Traceback (most recent call last):
  File "opendata.py", line 112, in <module>
    api_conn.get_data(unique_data_ids)
  File "opendata.py", line 92, in get_data
    raise Exception(err.format(result.status_code))
Exception: An error occurred during request: status 202
```

**Comment by NealHumphrey** [comment]
I have yet to re-encounter this error. 

One potential solution - instead of polling the server for the completion of the original request, if a 202 status is returned, just dump the old request and try again with a fresh request and hope it goes through immediately. Seems like nearly all the time it is going through. We will of course not want to risk an infinite loop so define a limited number of retries before giving up. 

Definitely want this handled in V2 before we deploy to a server so our get_api_data routine doesn't crash the server
