### ISSUE TITLE
get_api_data.py sporatically timing out on opendata class

### ISSUE THREAD

**Issue by jgordo04** [codefordc/housing-insights#294]
The opendata class is timing out in get_api_data.py SOMETIMES. It is timing out on the get statement (I think):
`result = self.get(self._urls[u], params=None)`

The following error is what it spits out:
```
The request for "opendata" failed. Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_api_data.py", line 101, in <module>
    get_multiple_api_sources(unique_data_ids,sample,output_type,db,debug, module_list)
  File "get_api_data.py", line 82, in get_multiple_api_sources
    raise e
  File "get_api_data.py", line 75, in get_multiple_api_sources
    api_method(unique_data_ids, sample, output_type, db=db)
  File "/Users/jamiegordonlipkin/projects/git/housing-insights/python/housinginsights/sources/opendata.py", line 65, in get_data
    result = self.get(self._urls[u], params=None)
  File "/Users/jamiegordonlipkin/projects/git/housing-insights/python/housinginsights/sources/base.py", line 96, in get
    return self.session.get(url, params=params, proxies=self.proxies, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 531, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

If you encounter this same issue, please post so we can try to get to the bottom of it.

**Comment by jkwening** [comment]
@jgordo04 what are the arguments you passed in `get_multiple_api_sources(unique_data_ids,sample,output_type,db,debug, module_list)` that triggered this? I'll see if I can replicate and help try and debug the issue tonight or over the weekend.

**Comment by jgordo04** [comment]
@jkwening . The module arguments were  ["opendata","DCHousing"] . And it was timing out/failing on opendata. Thanks for taking a look!

**Comment by jkwening** [comment]
closing - I wasn't able to replicate the error and haven't heard any new reports.
